#!/usr/bin/env bash
PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:~/bin
export PATH
clear
sh_ver="0.1"

#取系统信息
get_opsy() {
    [ -f /etc/redhat-release ] && awk '{print ($1,$3~/^[0-9]/?$3:$4)}' /etc/redhat-release && return
    [ -f /etc/os-release ] && awk -F'[= "]' '/PRETTY_NAME/{print $3,$4,$5}' /etc/os-release && return
    [ -f /etc/lsb-release ] && awk -F'[="]+' '/DESCRIPTION/{print $2}' /etc/lsb-release && return
}
opsy=$( get_opsy )
arch=$( uname -m )
lbit=$( getconf LONG_BIT )
kern=$( uname -r )

echo -e "\033[32m┌───────────── 达奚Linux一键管理脚本 [Ver ${sh_ver}] https://reokey.com ─────────────┐\033[0m"
echo -e "\033[32m│                                                                              │\033[0m"
echo -e "\033[32m│                                                                              │\033[0m"
echo -e "\033[32m│                                                       达奚瀚泽 TG:3727638611 │\033[0m"
echo -e "\033[32m└──────────────────────────────────────────────────────────────────────────────┘\033[0m"
echo -e "\033[32m系统: $opsy  架构: $arch[$lbit Bit]  内核: $kern\033[0m"
echo
echo -e "\033[33m┌──────────────────────────────────────────────────────────────────────────────┐\033[0m"
echo -e "\033[33m│                                                                              │\033[0m"
echo -e "\033[33m│                                                                              │\033[0m"
echo -e "\033[33m│                                                                              │\033[0m"
echo -e "\033[33m└──────────────────────────────────────────────────────────────────────────────┘\033[0m"
echo -e "\033[33m输入'0'升级脚本\033[0m"
echo
echo -e "\033[32m┌──────────────────────────────────────────────────────────────────────────────┐\033[0m"
echo -e "\033[32m│                                                                              │\033[0m"
echo -e "\033[32m│                                                                              │\033[0m"
echo -e "\033[32m│                                                                              │\033[0m"
echo -e "\033[32m│                                                                              │\033[0m"
echo -e "\033[32m│                                                                              │\033[0m"
echo -e "\033[32m│                                                                              │\033[0m"
echo -e "\033[32m└──────────────────────────────────────────────────────────────────────────────┘\033[0m"
echo -e "\033[32m请输入数字 [0-9]:\033[0m"
read num
case "$num" in
	[0] )
			Update_Shell
		;;
	[1] )
			rm -rf dx-sys
			curl -# -o dx-sys https://raw.githubusercontent.com/reokey/shell/master/dx/dx-sys
			sh dx-sys
		;;
	[2] )
			Update_Shell
		;;
	[3] )
			read -p "按任意键开始...或按 Ctrl+C 取消"
		;;
	[4] )
			read -p "按任意键开始...或按 Ctrl+C 取消"
		;;
	[5] )
			read -p "按任意键开始...或按 Ctrl+C 取消"
		;;
		*) echo -e "\033[31m选择错误,退出;请重新执行.\033[0m";;
	esac

Update_Shell(){
	echo -e "当前版本为 [ ${sh_ver} ]，开始检测最新版本..."
	sh_new_ver=$(wget --no-check-certificate -qO- "https://raw.githubusercontent.com/reokey/shell/master/dx/dx"|grep 'sh_ver="'|awk -F "=" '{print $NF}'|sed 's/\"//g'|head -1)
	[[ -z ${sh_new_ver} ]] && echo -e "${Error} 检测最新版本失败 !" && exit 0
	if [[ ${sh_new_ver} != ${sh_ver} ]]; then
		echo -e "发现新版本[ ${sh_new_ver} ]，是否更新？[Y/n]"
		stty erase '^H' && read -p "(默认: y):" yn
		[[ -z "${yn}" ]] && yn="y"
		if [[ ${yn} == [Yy] ]]; then
			wget -N --no-check-certificate https://raw.githubusercontent.com/reokey/shell/master/dx/dx && chmod +x dx
			echo -e "脚本已更新为最新版本[ ${sh_new_ver} ] !"
		else
			echo && echo "	已取消..." && echo
		fi
	else
		echo -e "当前已是最新版本[ ${sh_new_ver} ] !"
	fi
}