#!/usr/bin/env bash
PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:~/bin
export PATH
clear
sh_ver="0.1"

#取系统信息
get_opsy() {
    [ -f /etc/redhat-release ] && awk '{print ($1,$3~/^[0-9]/?$3:$4)}' /etc/redhat-release && return
    [ -f /etc/os-release ] && awk -F'[= "]' '/PRETTY_NAME/{print $3,$4,$5}' /etc/os-release && return
    [ -f /etc/lsb-release ] && awk -F'[="]+' '/DESCRIPTION/{print $2}' /etc/lsb-release && return
}
opsy=$( get_opsy )
arch=$( uname -m )
lbit=$( getconf LONG_BIT )
kern=$( uname -r )

echo -e "\033[32m┌───────────── 达奚Linux一键管理脚本 [Ver ${sh_ver}] https://reokey.com ─────────────┐\033[0m"
echo -e "\033[32m│                                                                              │\033[0m"
echo -e "\033[32m│    作者 萌咖  https://moeclub.org/2018/04/03/603/?v=244                      │\033[0m"
echo -e "\033[32m│                                                       达奚瀚泽 TG:3727638611 │\033[0m"
echo -e "\033[32m└──────────────────────────────────────────────────────────────────────────────┘\033[0m"
echo
echo -e "\033[32m系统: $opsy  架构: $arch[$lbit Bit]  内核: $kern\033[0m"
echo
echo -e "\033[32m 确保安装了所需软件:\033[0m"
echo -e "\033[32m     Debian/Ubuntu: apt-get install -y xz-utils openssl gawk file\033[0m"
echo -e "\033[32m     RedHat/CentOS: yum install -y xz openssl gawk file\033[0m"
echo -e "\033[32m 密码为: Vicer\033[0m"
echo -e "\033[33m┌──────────────────────────────────────────────────────────────────────────────┐\033[0m"
echo -e "\033[33m│         1 centos6 32         2 centos6 64         3 centos7 64               │\033[0m"
echo -e "\033[33m│         4 debian7 32         5 debian8 32         6 debian8 64               │\033[0m"
echo -e "\033[33m│         7 debian9 64         8 win2003 32         9 win2012 64               │\033[0m"
echo -e "\033[33m└──────────────────────────────────────────────────────────────────────────────┘\033[0m"
echo
echo -e "\033[32m 请输入数字 [0-9]或[a-z]:\033[0m"
read num
case "$num" in
			[1] )
				rm -rf dxhz_Install
				curl -# -o dxhz_Install https://raw.githubusercontent.com/reokey/shell/master/data/dxhz_Install
				bash dxhz_Install -c 6.8 -v 32 -a
		;;
			[2] )
				rm -rf dxhz_Install
				curl -# -o dxhz_Install https://raw.githubusercontent.com/reokey/shell/master/data/dxhz_Install
				bash dxhz_Install -c 6.9 -v 64 -a
		;;
			[3] )
				rm -rf dxhz_Install
				curl -# -o dxhz_Install https://raw.githubusercontent.com/reokey/shell/master/data/dxhz_Install
				bash dxhz_Install -c 7.4 -v 64 -a
		;;
			[4] )
				rm -rf dxhz_Install
				curl -# -o dxhz_Install https://raw.githubusercontent.com/reokey/shell/master/data/dxhz_Install
				bash dxhz_Install -d 7 -v 32 -a
		;;
			[5] )
				rm -rf dxhz_Install
				curl -# -o dxhz_Install https://raw.githubusercontent.com/reokey/shell/master/data/dxhz_Install
				bash dxhz_Install -d 8 -v 32 -a
		;;
			[6] )
				rm -rf dxhz_Install
				curl -# -o dxhz_Install https://raw.githubusercontent.com/reokey/shell/master/data/dxhz_Install
				bash dxhz_Install -d 8 -v 64 -a
		;;
			[7] )
				rm -rf dxhz_Install
				curl -# -o dxhz_Install https://raw.githubusercontent.com/reokey/shell/master/data/dxhz_Install
				bash dxhz_Install -d 9 -v 64 -a
		;;
			[8] )
				rm -rf dxhz_Install
				curl -# -o dxhz_Install https://raw.githubusercontent.com/reokey/shell/master/data/dxhz_Install
				bash dxhz_Install --ip-addr x.x.x.x --ip-gate x.x.x.x --ip-mask x.x.x.x -dd 'https://moeclub.org/get-win7embx86-auto'
				
		;;
			[9] )
				rm -rf dxhz_Install
				curl -# -o dxhz_Install https://raw.githubusercontent.com/reokey/shell/master/data/dxhz_Install
				bash dxhz_Install --ip-addr x.x.x.x --ip-gate x.x.x.x --ip-mask x.x.x.x -dd 'https://moeclub.org/get-win7embx86-auto'
		;;
		*) echo -e "\033[31m 输入错误,请重新输入.\033[0m";;
	esac
